services:
  - type: web
    name: stock-management-frontend
    env: static
    buildCommand: npm run build
    publishDir: dist/stock-management-frontend/browser
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
