services:
  - type: web
    name: stock-management-frontend
    env: static
    buildCommand: npm run build:prod
    publishDir: dist/stock-management-frontend/browser
    nodeVersion: 18.17.0
    envVars:
      - key: NODE_ENV
        value: production
